### ISSUE TITLE
Cannot load StringPrep-0.5.4 bindings (using fallback).

### ISSUE THREAD

**Issue by tsuncp** [node-xmpp/node-xmpp-client#100]
var Client = require('node-xmpp-client')

var options = {
    type: 'client',
    jid: '*************@gcm.googleapis.com',
    password: '***************',
    port: 5235,
    host: 'gcm.googleapis.com',
    legacySSL: true,
    preferredSaslMechanism : 'PLAIN'
};
var Client = new Client(options);
Client.on('online',
  function () {
    console.log("online");
});

For testing, only above code is used.

Cannot load StringPrep-0.5.4 bindings (using fallback). You may need to `npm ins
tall node-stringprep`

I am using node js 0.12 and the latest node-xmpp-client

**Comment by lloydwatkin** [comment]
Please see installation instructions for node-stringprep here: http://node-xmpp.org/doc/stringprep.html

**Comment by tsuncp** [comment]
can stringprep be worked in windows platform?
I can install node-stringprep successfully. However when i run it

var StringPrep = require('node-stringprep').StringPrep;
var prep = new StringPrep('nameprep');
prep.prepare('Äffchen')  // => 'äffchen'

Cannot load StringPrep-0.7.0 bindings (using fallback). You may need to `npm ins
tall node-stringprep`

same error is displayed. Do I need to install libicu or sth?  But I only find other platform but not windows in the instructions

**Comment by lloydwatkin** [comment]
You can actually get away without having it installed (we have javascript fallbacks), so you could happily ignore the warning if you prefer.  I'm unsure about installing on windows I'm afraid, does the libicu website provide any help?
