### ISSUE TITLE
Problem with deps

### ISSUE THREAD

**Issue by giladbeeri** [node-xmpp/node-xmpp-client#104]
My package depends on `node-xmpp-client` version `1.0.0-alpha15`. This version depends on `node-xmpp-core` version `1.0.0-alpha10`. I found out that originally it downloaded the correct version, but if I run `npm install` now, it downloads *`node-xmpp-core 1.0.0-alpha14`*, even though it still points to `1.0.0-alpha10`.

The problem is that the dependency uses `~`, which means it is allowed to download newer versions. It should use an exact version.

**Comment by lloydwatkin** [comment]
What is wrong with it pulling newer versions of the alphas?

**Comment by giladbeeri** [comment]
The consumer (the developer which uses that package) can't reproduce his build. That's what happened to me. Apparently something changed in alpha14 (vs. alpha10) that broke my code, and it surprised me and took me some time to find out because I wasn't expected an update.

Once you publish a version, you should either fix all of its dependencies (i.e., don't use `~`, `^`, `*`, `x` and the like in the dependency versions), or just use `npm shrinkwrap`, which is meant for exactly that.

**Comment by giladbeeri** [comment]
See https://github.com/node-xmpp/node-xmpp-core/issues/63

**Comment by lloydwatkin** [comment]
Hi @giladbeeri, @sonnyp has been hard at work, can you try with the latest version (1.x) and report back if not all is ok. Thanks!
