### ISSUE TITLE
gyp ERR! build error 

### ISSUE THREAD

**Issue by cgianelle** [node-xmpp/node-xmpp-client#107]
Fails when trying to install node-xmpp-client on Mac (OSX v 10.9.5) - node-gyp rebuild specifically. I have also seen this fail on Ubuntu 14.04. Same reason.

Node version: v0.12.0

Install output:
GIANELC-M-J09Z:FunWithNode gianelc$ npm install node-xmpp-client
 
> node-stringprep@0.7.0 install /Users/gianelc/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
-

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gianelc/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/node-stringprep
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
|
> iconv@2.1.6 install /Users/gianelc/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/gianelc/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat/node_modules/iconv
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node-xmpp-client"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! node-stringprep@0.7.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-stringprep@0.7.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gianelc/Documents/Muscovy/FunWithNode/npm-debug.log
GIANELC-M-J09Z:FunWithNode gianelc$

**Comment by lloydwatkin** [comment]
Is this your issue "Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo."

**Comment by cgianelle** [comment]
don't know, is it? I'm new to nodejs. I was able to install websocket without any issue, but I get the above when trying to install node-xmpp-client.

**Comment by lloydwatkin** [comment]
I'd suggest you try running xcode from your laptop, going through any set up and then trying again (xcode isn't nodejs related* its a mac thing).

* not quite true, but true enough.

**Comment by cgianelle** [comment]
Thanks, I'll give it a try.

**Comment by cgianelle** [comment]
Thanks, again. I had to accept a license agreement and then everything installed properly.
