### ISSUE TITLE
Misused semver in versions like 1.0.0-alpha20

### ISSUE THREAD

**Issue by arty-name** [node-xmpp/node-xmpp-client#108]
Apparently the `-alpha20` appendage is compared as string with other versions, so it ends up being less then `-alpha9`. Check it out on [semver calculator](http://semver.npmjs.com/). As a result when I have `^1.0.0-alpha20` in my `package.json` and do `npm update` I end up with version `^1.0.0-alpha9`

**Comment by lloydwatkin** [comment]
We've moved to 1.x now, and we'll use proper alpha versioning in semver next time :)
