### ISSUE TITLE
Translate gtalk JID to gmail

### ISSUE THREAD

**Issue by amirmamaghani** [node-xmpp/node-xmpp-client#115]
I have one big problem - I'm working on chat app and I need to be able to write on gtalk to somebody with JID johndow@gmail.com BUT gtalk uses some weird kind of JID like longandveryanoyinghash@public.talk.google.com . It's ok when messages come from/to this address but initially I need to be able to pair those two addresses together. 
Is there any way to retrieve what gtalk JID does johndow@gmail.com have?

**Comment by lloydwatkin** [comment]
That's probably a question for google rather than us I'm afraid. I'm also unsure how much longer google will support XMPP connections to their hangouts service.

**Comment by hhellbusch** [comment]
@amirmamaghani any luck on this?  Came across the same issue.  tried using https://github.com/simple-xmpp/node-simple-xmpp as well with no success.
