### ISSUE TITLE
How can I print ejabbered offline messages using node-xmpp

### ISSUE THREAD

**Issue by pokal4u** [node-xmpp/node-xmpp-client#116]
HI,
I am sending messages from 'admin@localhost' to 'test@localhost', and I able to see these messages in ejabbered admin panel.

My code:

var xmpp = require('node-xmpp');
var c2s = new xmpp.C2SServer({
    port: 8088,
    domain: 'localhost'
});
c2s.on("connect", function() {
    c2s.on("register", function(opts, cb) {
        console.log("REGISTER");
		cb(true);
    });	
	client = new xmpp.Client({jid: 'test@localhost', password: 'test123'});
    client.on("authenticate", function(opts, cb) {
        console.log("AUTH" + opts.jid + " -> " +opts.password); 
		cb(null, opts); 
    });	
	client.on('error', function(err) {
		console.log("error:"+err.toString());
	});
	client.on('online', function() {
		console.log("online");
		var stanza = new xmpp.Element('message', { to: 'admin@localhost', type: 'chat' }).c('body').t('test');//, 'xml:lang': 'ko'
		client.send(stanza);
	});
	client.addListener('stanza', function(stanza) {
		 console.log("stanza" + stanza);
		 console.log(stanza.children[1].children);
		 client.end();
	});
    client.on("disconnect", function(client) {
        console.log("DISCONNECT");
    });
});

when run this code in browser http://www/domain.com:8088, messages sent succesfully and in console print "online" message only, but  getting error in browser like

![error](https://cloud.githubusercontent.com/assets/498771/8669142/9158ceca-2a2f-11e5-8ddd-66b7da90f64d.png)

Please let me know if my code was wrong.

And how to print those messages in browser?

Thanks

**Comment by lloydwatkin** [comment]
It looks like the server is telling you you've sent invalid XML to it.

**Comment by pokal4u** [comment]
Your saying problem with below lines?

var stanza = new xmpp.Element('message', { to: 'admin@localhost', type: 'chat' }).c('body').t('test');
client.send(stanza);

can you provide valid format?

**Comment by sonnyp** [comment]
@pokal4u 

client.send(stanza.root()) should do the trick

**Comment by pokal4u** [comment]
no.. getting same error

**Comment by pokal4u** [comment]
anybody please help me...

**Comment by pokal4u** [comment]
Also check ejabbered Listened Ports

![ejab](https://cloud.githubusercontent.com/assets/498771/8692552/e31359d4-2aec-11e5-88ac-a06a1339d014.png)

**Comment by lloydwatkin** [comment]
In your examples you are attempting to run a server in the browser, this will not work - maybe one day :)

You need to remove the server code.

In order to receive the offline messges that you've sent you'll need to open a new client connection, connect to the server with the appropriate account, and send a presence stanza. The server will then push your offline messages to you.

**Comment by pokal4u** [comment]
I modified code like:

var xmpp = require('node-xmpp');
var client = new xmpp.Client({    
	jid: 'admin@localhost',
	password: 'admin123',
	port: 8088,
    domain: 'localhost'
});	
client.on('error', function(err) {
	console.log("error::"+err.toString());
});
client.on("authenticate", function(opts, cb) {
	console.log("AUTH" + opts.jid + " -> " +opts.password); 
	cb(null, opts); 
});	
client.on('online', function() {
	console.log("online");
	var stanza = new xmpp.Element('message', { to: 'test@localhost', type: 'chat' }).c('body').t('test');//, 'xml:lang': 'ko'
	client.send(stanza);	
	var stanza1 = new xmpp.Element('presence', { }).c('show').t('chat').up().c('status').t('test....');
	client.send(stanza1);	
});
client.addListener('stanza', function(stanza) {
	 console.log("stanza:" + stanza);
	 console.log("from:" + stanza.attrs.from);
	 console.log("to:" + stanza.attrs.to);
	 console.log("message:" +stanza.children[1].children);
	 client.end();
});
client.on("disconnect", function(client) {
	console.log("DISCONNECT");
});

Now getting error 

![node](https://cloud.githubusercontent.com/assets/498771/8694075/d37c1a8a-2af9-11e5-9755-03171375fc18.png)

**Comment by pokal4u** [comment]
anybody help me.....

**Comment by lloydwatkin** [comment]
There's no need for this:

```
client.on("authenticate", function(opts, cb) {
console.log("AUTH" + opts.jid + " -> " +opts.password); 
cb(null, opts); 
}); 
```

The error you are receiving says you are attempting to send a stanza which the server is unable to handle for some reason.

**Comment by pokal4u** [comment]
And console.log event fired only "online", what about remaining ?

**Comment by pokal4u** [comment]
what is that reason?

anybody help me...

**Comment by lloydwatkin** [comment]
If you run your script with DEBUG=* e.g.

```javascript
DEBUG=* node index
```

Then you'll see everything going back and forth. It just may be that the server isn't sending you any stanzas.
