### ISSUE TITLE
XMPP Authentication Failure with Prosody

### ISSUE THREAD

**Issue by gpadbidri** [node-xmpp/node-xmpp-client#125]
HI I am using the Node XMPP Client Module to authenticate to the Prosody Server and then send a Stanza...However, eventhough the credentials are CORRECT, I get an XMPP Authentication Failure. Why is it so ? Am I missing on something ? OR is there any Prosody Configuration that needs to be done to allow authentication via this module ? Let me knoe your comments on the same. Thanks !

Screenshot of the STANZA response I get in Index.js -> _handleAuthState() : http://screencast.com/t/Eh108nSW

Code : 
    var Client = require('../node-xmpp-client/index.js');
    var connection = new Client({
           jid: 'username@chatDomain',
           password: password
    });        

connection.addListener('online',function() {
        console.log("Connected...........");
        connection.send(new ltx.Element('presence',{to:acceptingUser,type:'subscribed'}));
});            
                    
connection.addListener('error',function(e) {
         console.log('In Error : ' + e);
});

**Comment by lloydwatkin** [comment]
There's no special prosody config required, its all standard XMPP. From the screenshot I can just tell that your authentication failed but not why. Do Prosody logs help? Can you login via a standard XMPP client to the same account?

We run our test suite against an install of prosody so I'm 100% confident the issue isn't with `node-xmpp-client` (check out the tests directory - includes our config).
