### ISSUE TITLE
Error connecting Client with version 2.0

### ISSUE THREAD

**Issue by bgrins** [node-xmpp/node-xmpp-client#134]
Hi, I just installed 2.0 and when running a fairly simple test, I was receiving "XMPP authentication failure".  

    var client = new Client({
        jid: 'test@localhost',
        password: 'password',
        preferred: 'PLAIN',
        host: 'hostname',
    });

    client.on('error', function(e) {
        console.error(e); // "XMPP authentication failure"
    })

I tried changing the preferred option and modifying the jid in a variety of ways but always ended up with the error.

Looking into the logs on the server, I was seeing this response:

I(<0.1718.0>:ejabberd_c2s:649) : ({socket_state,tls,{tlssock,#Port<0.2544>,#Port<0.2546>},<0.1717.0>}) Failed authentication for undefined@localhost

After switching back to version 1, the connection was successful again.

**Comment by sonnyp** [comment]
sorry about that fixed in https://github.com/node-xmpp/node-xmpp-client/pull/135 and released as 2.0.1

**Comment by bgrins** [comment]
Thanks!
