### ISSUE TITLE
Node-xmpp-client digest-md5 not working

### ISSUE THREAD

**Issue by rohitmanusis** [node-xmpp/node-xmpp-client#137]
I tried to login using following code but it's not working. Error : XMPP Authentication Failure. I have installed OpenFire. Server is properly working when i tried to connect with JAVA.

var Client = require('node-xmpp-client');
var cl = new Client({
  jid : "ttest",
  password : '123456',
  host :'localhost',
  reconnect : true,
});

cl.on('online', function() {
  console.log('online');
});

cl.on('error', function(err){
  console.log('err : ', err);
});

cl.on('stanza', function(stanza) {
    console.log('Incoming stanza: ', stanza.toString());
});

cl.on('connect', function() {
    console.log('connnecting....');
});

cl.on('reconnect', function() {
    console.log('reconnnecting....');
});

**Comment by sonnyp** [comment]
what is your node-xmpp-client version?

**Comment by rohitmanusis** [comment]
I tried using 2.0.2 but it did not work.

**Comment by sonnyp** [comment]
how do you it's using digest-md5 ?

**Comment by rohitmanusis** [comment]
I checked code internally and found digest-md5 is the default mechanism.  Check this file 

node-xmpp-client\lib\Client.js : 194 (line number)

No it's not working with preferredSaslMechanism: 'PLAIN' also.

**Comment by sonnyp** [comment]
most probably your password/jid is wrong, can you double check?

If it's not the case please give me your openfire version and configuration

**Comment by rohitmanusis** [comment]
My password/jid is correct. I am able to connect using JAVA.

Openfire version : Openfire 3.10.2

**Comment by sonnyp** [comment]
In your code you have ``` jid : "ttest",``` it should be ``` jid : "ttest@localhost",```

can you try again with @localhost ?

**Comment by rohitmanusis** [comment]
Yes, It's working now. Thanks Man!
Can you please let me know why it was not working without  'PLAIN' ?

**Comment by sonnyp** [comment]
remove preferedSaslMechanism and try again

The issue was the missing domain in the jid
ttest instead of ttest@localhost

**Comment by rohitmanusis** [comment]
No, it's not working without "PLAIN"

**Comment by sonnyp** [comment]
even with ttest@localhost as jid?

**Comment by rohitmanusis** [comment]
var Client = require('node-xmpp-client');

var cl = new Client({
  jid : "ttest@localhost",
  password : '123456',
});

Not it's not working without "PLAIN".

**Comment by sonnyp** [comment]
if it doesn't work with digest it could be an incompatibility between node-xmpp-client and openfire; I've file https://github.com/node-xmpp/node-xmpp-client/issues/138
