### ISSUE TITLE
stanza.getAttribute is not a function

### ISSUE THREAD

**Issue by austinkelleher** [node-xmpp/node-xmpp-client#143]
I upgraded to the newest version of node-xmpp-client from 1.0.0-alpha23, and I began receiving the following error:

```
stanza.getAttribute is not a function
/node_modules/node-xmpp-client/lib/Client.js:222:14
```

Example of code:

```javascript
client.on('stanza', function(stanza) {
    var type = stanza.getAttribute('type');
});
```

Could it be possibly related to [this](https://github.com/node-xmpp/node-xmpp-client/commit/fc149e6babfb0d1a1bb2ebf8664a04dbfdfef040#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R31) change? What is the proper way to `getAttribute` now?

**Comment by sonnyp** [comment]
Hello,

The DOM API was moved to a different class.

Please use stanza.attrs.type or stanza.attr('type')

**Comment by austinkelleher** [comment]
:+1:

**Comment by lloydwatkin** [comment]
We shouldn't be using `Element.js` from `ltx` but `DOMElement.js` this is required for use in the browser.

**Comment by sonnyp** [comment]
@lloydwatkin why is DOMElement.js required for use in the browser?

It's just a DOM API compatible wrapper around Element.
