### ISSUE TITLE
v3.0.0 gets invalid namespace for connections with Jitsi

### ISSUE THREAD

**Issue by jmcoimbra** [node-xmpp/node-xmpp-client#159]
Hello guys,

We are using your module in a product we are designing for Jitsi Videobridge, but after we have changed for v3.0.0 we have started getting _stream:error_ for a _invalid-namespace_ just for instantiating a connection.

```javascript
var Client = require('node-xmpp-client');
(...)
var client = new Client({
  jid: Config.jicofoDomain,
  preferredSaslMechanism: 'ANONYMOUS',
  reconnect: true,
  wait: 30,
  websocket: {
    url: 'ws://' + Config.jicofoDomain + ':5280/xmpp-websocket'
  }
});
```

Changing to your tag v2.1.0 we are OK.

**Comment by sonnyp** [comment]
hmmm node-xmpp-client 3 WebSocket now use http://tools.ietf.org/html/rfc7395 and support for previous draft was removed, maybe jitsi doesn't support final RFC?

**Comment by jmcoimbra** [comment]
Hey, thanks for this heads up.

We use [Prosody](https://prosody.im). It seems they are on the old draft since their last release was "2015-03-26".

Thanks

**Comment by sonnyp** [comment]
@jmcoimbra indeed, prosody 0.10 works fine with node-xmpp-client 3
I recommend you to use node-xmpp-client 2 until you're able to switch to prosody 0.10

**Comment by jmcoimbra** [comment]
OK, thank you for helping me out!
