### ISSUE TITLE
Turn on Logging

### ISSUE THREAD

**Issue by brbrr** [node-xmpp/node-xmpp-client#170]
Hi. Im quite new to node, so I could miss something.

I'm looking for a way to log client actions like sending/receiving stanza's, etc.
Pls point me where to look for. 
Also, I was not be able to find any api docs for this package. is there any?

Thanks!

**Comment by sonnyp** [comment]
>  Also, I was not be able to find any api docs for this package. is there any?

check http://node-xmpp.org/doc/client.html and https://github.com/node-xmpp/node-xmpp-client/tree/master/examples

> I'm looking for a way to log client actions like sending/receiving stanza's, etc.
```
client.on('stanza', function (stanza) {
  console.log('IN', stanza.toString())
})

var _send = client.send
client.send = function(stanza) {
  _send.call(client, stanza)
  console.log('OUT', stanza.toString())
})
```

**Comment by lloydwatkin** [comment]
also you can run your code with the environment variable `DEBUG` set to `*`

**Comment by brbrr** [comment]
@lloydwatkin awesome, thanks! that's should work.

Also, to use debug in repl - just start node console like `$DEBUG=* node`
