### ISSUE TITLE
Does this client support websocket connection to Openfire XMPP?

### ISSUE THREAD

**Issue by wyattbiker** [node-xmpp/node-xmpp-client#172]
I am stuck. I was using node-strophe, but it doesn't support websockets at this point (I don;t think it's even maintained). I am debating of switching to just pure XMPP for my application. Does this client support xmpp over websocket?

Thanks!

**Comment by sonnyp** [comment]
yes see websocket http://node-xmpp.org/doc/client.html option

Strophe.js does support XMPP transport, maybe node-strophe is not up do date?
I'd recommend stanza.io or xmpp-ftw though.

**Comment by wyattbiker** [comment]
Unfortunately node-strophe is not up to date. So i shot my self in the foot because websockets came as new requirement. I am hoping the developer will be able to update it soon. 

I have a custom XEP-XXXX that is implemented. Will node-xmpp support unkown XEPs? Is there a way to do it?

**Comment by lloydwatkin** [comment]
As you simply send and receive stanzas its up to the developer to support XEPs :)

Have you raised an issue for the maintainer of `node-strophe` about its out of date state?
