### ISSUE TITLE
Online event emitted but not connected

### ISSUE THREAD

**Issue by kamijoutouma** [node-xmpp/node-xmpp-client#197]
I use ejabberd for my xmpp server.

I cant get node xmpp client to connect via bosh without giving an internal server error. and when i try to connect via the normal method it sends "online" but its not actually connected.

Is there a bug in the connection module. Also 
```
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
online
```

That might have something to do with it.

**Comment by sonnyp** [comment]
You can ignore the warning for now it's unrelated. 

We need more information.

Use export debug=* before running your script to log debug messages and paste them here.
Also how do you know you're not really connected when it emits the online event?

**Comment by kamijoutouma** [comment]
I know because my pidgin client never once showed the account i had the
script on come online.
And i'll do it once i'm at work.

**Comment by sonnyp** [comment]
The script client has to send a presence for the account on pidgin to see the it online.

**Comment by kamijoutouma** [comment]
Why is that not documented?

**Comment by sonnyp** [comment]
@kamijoutouma it's not a node-xmpp thing, it's how XMPP works

**Comment by kamijoutouma** [comment]
Is that also the reason no stanza is recieved?

**Comment by sonnyp** [comment]
@kamijoutouma if it's a message, yes

**Comment by sonnyp** [comment]
I recommend this book to learn about XMPP

https://books.google.de/books?id=SG3jayrd41cC&printsec=frontcover&dq=xmpp+definitive+guide&hl=de&ei=SaogTPr0NdeUOMzwpS0&sa=X&oi=book_result&ct=result#v=onepage&q&f=false

**Comment by sonnyp** [comment]
Also

http://www.adarshr.com/fun-with-xmpp-and-google-talk
and
http://www.adarshr.com/fun-with-xmpp-and-google-talk-part-2

**Comment by kamijoutouma** [comment]
Thx
