### ISSUE TITLE
Duplicate events

### ISSUE THREAD

**Issue by piranna** [node-xmpp/node-xmpp-client#49]
On BOSHConnection class, the methods processResponse(), mayRequest() and end() are dispatching ```disconnect```, ```close``` & ```end``` events, making their callbacks to being called several times. This should be checked and prevented so they are only dispatched once.

**Comment by sonnyp** [comment]
@piranna thanks this is actually an issue on ```node-xmpp-core``` with our ```reconnect``` fork

See https://github.com/node-xmpp/node-xmpp-core/issues/59
