### ISSUE TITLE
Bosh + Sasl

### ISSUE THREAD

**Issue by chris-rock** [node-xmpp/node-xmpp-client#51]
The current bosh client does not work with properly with sasl authentication. It should generate 

```code
<body rid="122" sid="abc" xmpp:restart="true" .. />
```

Additionally it looks like Bosh and Websockets do not use the normal Socket Connection. I think this should be harmonized in order to implement core features only once. 

Have I missed something?

**Comment by sonnyp** [comment]
xmpp restart isn't mandatory. I'm working on this to pass node-xmpp-server BOSH tests.

@mweibel started work on this here: https://github.com/node-xmpp/node-xmpp-client/pull/85

I'm taking over.

**Comment by sonnyp** [comment]
Fixed.
PR is https://github.com/node-xmpp/node-xmpp-client/pull/91 and has been merged.
