### ISSUE TITLE
npm Install issue : Failed at the node-stringprep@0.5.4 install script

### ISSUE THREAD

**Issue by gowthaman-i2i** [node-xmpp/node-xmpp-client#80]
node -v0.10.28
npm  - 1.4.9

Error:

> node-stringprep@0.5.4 install /home/gowthaman/GProjects/xmppClient/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/node-stringprep
> node-gyp rebuild

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/home/gowthaman/.nvm/v0.10.28/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "node" "/home/gowthaman/.nvm/v0.10.28/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gowthaman/GProjects/xmppClient/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/node-stringprep
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! node-stringprep@0.5.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-stringprep@0.5.4 install script.
npm ERR! This is most likely a problem with the node-stringprep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-stringprep
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-40-generic
npm ERR! command "/home/gowthaman/.nvm/v0.10.28/bin/node" "/home/gowthaman/.nvm/v0.10.28/bin/npm" "i"
npm ERR! cwd /home/gowthaman/GProjects/xmppClient
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm http 200 https://registry.npmjs.org/debug/-/debug-2.1.0.tgz

> node-expat@2.3.3 install /home/gowthaman/GProjects/xmppClient/node_modules/ltx/node_modules/node-expat
> node-gyp rebuild

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/home/gowthaman/.nvm/v0.10.28/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "node" "/home/gowthaman/.nvm/v0.10.28/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gowthaman/GProjects/xmppClient/node_modules/ltx/node_modules/node-expat
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 

> node-expat@2.3.3 install /home/gowthaman/GProjects/xmppClient/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat
> node-gyp rebuild

Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/home/gowthaman/.nvm/v0.10.28/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 3.13.0-40-generic
gyp ERR! command "node" "/home/gowthaman/.nvm/v0.10.28/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/gowthaman/GProjects/xmppClient/node_modules/node-xmpp-client/node_modules/node-xmpp-core/node_modules/ltx/node_modules/node-expat
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok

**Comment by lloydwatkin** [comment]
@gowthaman-i2i can you try with the latest version please?

Otherwise closing
