### ISSUE TITLE
Does not work in the browser

### ISSUE THREAD

**Issue by DadaMonad** [node-xmpp/node-xmpp-client#87]
I'm trying to get this to work.

I installed `node-xmpp-client` (v1.0.0-alpha19) with npm (v1.4.28, and node v0.10.33 )

The instructions on your website do not work (for me):
```
var Client = require('node-xmpp-client')
var client = new Client(...my settings...)
```
I browserified my file, but it does not work:
I get an uncought Error:
```
Uncaught TypeError: undefined is not a function         srv.js:47 
```

I tried the browserified file. But, again, I get a TypeError:
```
Uncaught TypeError: Cannot read property 'Element' of undefined         node-xmpp-browser.js:11 
```

So far I also tried the version that I found with bower (node-xmpp-client@v1.0.2 - this should be stable, right?).

Am I doing something wrong here? I got it running with nodejs tough (the exact same file).
Could you point me to some documentation that explains how to do that in the browser?

**Comment by DadaMonad** [comment]
I just read in #65 that you actually do not support the browser in the 1.0.0- branch. 
Could you please indicate that somewhere.
This issue can be closed then.

**Comment by lloydwatkin** [comment]
Hi,

We are supporting the browser with the 1.0.0 branch and have automated tests for this. Could you download the repository from here and try `node-xmpp-browser.js` which is pushed back into the repo from travisci

**Comment by lloydwatkin** [comment]
Also what settings are you using? (Obviously redact password field)

**Comment by DadaMonad** [comment]
I'm happy to hear that :)

Feel free to try it yourself:
```
var client = new XMPP.Client({
  jid: '@yatta.ninja',
  preferredSaslMechanism: "ANONYMOUS",
  preferred: "ANONYMOUS",
  websocketURL: 'wss:yatta.ninja:5281/xmpp-websocket'
});

client.on('online', function() {
  return console.log('online');
});

client.on('stanza', function() {
  return console.log('Incoming stanza: ', stanza.toString());
});
```

- I also tried to authenticate with username+password.
- I tried non-secure socket 'ws:yatta.ninja:5280/xmpp-websocket'
- I have a Prosody server running (v0.10).
- Strophejs works with my configuration (so my server is probably well configured).

**Comment by lloydwatkin** [comment]
Ok, currently only bosh works (actually I haven't tested websockets) and does not work with digest-md5 (only plain - there is an issue with browserified md5 library @legastero has investigated).

The new option hash is:

```javascript
bosh: {
  url: '...bosh url...'
}
```

Websocket URL would be:

```javascript
websocket: {
  url: '...websocket url...'
}
```

But I haven't confirmed this works yet.

**Comment by DadaMonad** [comment]
In your [documentation](http://node-xmpp.github.io/doc/nodexmppclient.html), you specify `websocketsURL` as a options parameter:
```
websocketsURL [String]: A websocket URL endpoint to use (used in preference to a socket and BOSH endpoint if provided)
```

When I use `websocket` like this, it works.
```
websocket: 'wss:yatta.ninja:5281/xmpp-websocket'
```

**Comment by DadaMonad** [comment]
Alright, then this is fine for me. Thanks for your answer!

**Comment by lloydwatkin** [comment]
It needs to be better, I am trying when I get spare time :)
