### ISSUE TITLE
fails on node 0.11

### ISSUE THREAD

**Issue by chris-rock** [node-xmpp/node-xmpp-client#88]
@lloydwatkin current tests fail on node 0.11 any ideas?

**Comment by sonnyp** [comment]
node 0.12 as well

**Comment by lloydwatkin** [comment]
I'm not concerned about 0.11 and I think we should remove from testing 0.12
and iojs are concerns seems to be some event firing issues going on

**Comment by chris-rock** [comment]
Currently only 0.8 and iojs fail. Drop support for 0.8 and do iojs later?

**Comment by sonnyp** [comment]
@chris-rock for 0.12 the issue was fixed in https://github.com/node-xmpp/ltx/commit/2ae7db4146791026c48a1ff63018fbef041bb97f

+1 to drop 0.8

**Comment by lloydwatkin** [comment]
Have just update node-xmpp-core tests and they are now passing. Reinstated 0.8 there to see what happens as there's no reason that shouldn't pass too.
